version: "3.8"

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: natechoe.dev
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
        # SMTP

      - "143:143"
      - "993:993"
      # IMAP
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ONE_DIR=1
      - ENABLE_AMAVIS=1
      - ENABLE_CLAMAV=0
      - ENABLE_POP3=0
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_MECHANISMS=rimap
      - SASLAUTHD_MECH_OPTIONS=127.0.0.1

      - SSL_TYPE=letsencrypt
      - SPOOF_PROTECTION=1
      - ENABLE_SPAMASSASSIN=1
      - POSTFIX_INET_PROTOCOLS=ipv4
      - DOVECOT_INET_PROTOCOLS=ipv4
    restart:
      always
